WINGDIAPI int WINAPI AddFontResourceU(IN LPCSTR);

WINGDIAPI HMETAFILE WINAPI CopyMetaFileU( IN HMETAFILE, IN LPCSTR);

WINGDIAPI HDC     WINAPI CreateDCU( IN LPCSTR, IN LPCSTR, IN LPCSTR, IN CONST DEVMODEA *);

WINGDIAPI HFONT   WINAPI CreateFontIndirectU( IN CONST LOGFONTA *);

WINGDIAPI HFONT   WINAPI CreateFontU( IN int, IN int, IN int, IN int, IN int, IN DWORD,
                             IN DWORD, IN DWORD, IN DWORD, IN DWORD, IN DWORD,
                             IN DWORD, IN DWORD, IN LPCSTR);

WINGDIAPI HDC     WINAPI CreateICU( IN LPCSTR, IN LPCSTR, IN LPCSTR, IN CONST DEVMODEA *);

WINGDIAPI HDC     WINAPI CreateMetaFileU( IN LPCSTR);

WINGDIAPI BOOL    WINAPI CreateScalableFontResourceU( IN DWORD, IN LPCSTR, IN LPCSTR, IN LPCSTR);

WINSPOOLAPI int  WINAPI DeviceCapabilitiesU( IN LPCSTR, IN LPCSTR, IN WORD,
                                OUT LPSTR, IN CONST DEVMODEA *);

WINGDIAPI int  WINAPI EnumFontFamiliesExU( IN HDC, IN LPLOGFONTA, IN FONTENUMPROCA, IN LPARAM, IN DWORD);

WINGDIAPI int  WINAPI EnumFontFamiliesU( IN HDC, IN LPCSTR, IN FONTENUMPROCA, IN LPARAM);

WINGDIAPI int  WINAPI EnumFontsU( IN HDC, IN LPCSTR,  IN FONTENUMPROCA, IN LPARAM);

WINGDIAPI BOOL  WINAPI GetCharWidthU( IN HDC, IN UINT, IN UINT, OUT LPINT);

WINGDIAPI BOOL  WINAPI GetCharWidth32U( IN HDC, IN UINT, IN UINT,  OUT LPINT);

WINGDIAPI BOOL  APIENTRY GetCharWidthFloatU( IN HDC, IN UINT, IN UINT, OUT PFLOAT);

WINGDIAPI BOOL  APIENTRY GetCharABCWidthsU( IN HDC, IN UINT, IN UINT, OUT LPABC);

WINGDIAPI BOOL  APIENTRY GetCharABCWidthsFloatU( IN HDC, IN UINT, IN UINT, OUT LPABCFLOAT);

WINGDIAPI DWORD WINAPI GetGlyphOutlineU( IN HDC, IN UINT, IN UINT, OUT LPGLYPHMETRICS, IN DWORD, OUT LPVOID, IN CONST MAT2 *);

WINGDIAPI HMETAFILE   WINAPI GetMetaFileU( IN LPCSTR);

WINGDIAPI UINT APIENTRY GetOutlineTextMetricsU( IN HDC, IN UINT, OUT LPOUTLINETEXTMETRICA);

WINGDIAPI BOOL  APIENTRY GetTextExtentPointU(
                    IN HDC,
                    IN LPCSTR,
                    IN int,
                    OUT LPSIZE
                    );

WINGDIAPI BOOL  APIENTRY GetTextExtentPoint32U(
                    IN HDC,
                    IN LPCSTR,
                    IN int,
                    OUT LPSIZE
                    );

WINGDIAPI BOOL  APIENTRY GetTextExtentExPointU(
                    IN HDC,
                    IN LPCSTR,
                    IN int,
                    IN int,
                    OUT LPINT,
                    OUT LPINT,
                    OUT LPSIZE
                    );

WINGDIAPI DWORD WINAPI GetCharacterPlacementU(  IN HDC, IN LPCSTR, IN int, IN int, IN OUT LPGCP_RESULTSA, IN DWORD);

WINGDIAPI DWORD WINAPI GetGlyphIndicesU( IN HDC, IN LPCSTR, IN int, OUT LPWORD, IN DWORD);

WINGDIAPI int  WINAPI AddFontResourceExU( IN LPCSTR, IN DWORD, IN PVOID);

WINGDIAPI BOOL WINAPI RemoveFontResourceExU( IN LPCSTR, IN DWORD, IN PVOID);

WINGDIAPI HFONT  WINAPI CreateFontIndirectExU( IN CONST ENUMLOGFONTEXDVA *);

WINGDIAPI BOOL WINAPI LineDDU( IN int, IN int, IN int, IN int, IN LINEDDAPROC, IN LPARAM);

WINGDIAPI HDC  WINAPI ResetDCU(IN HDC, IN CONST DEVMODEA *);

WINGDIAPI BOOL WINAPI RemoveFontResourceU(IN LPCSTR);

WINGDIAPI HENHMETAFILE WINAPI CopyEnhMetaFileU( IN HENHMETAFILE, IN LPCSTR);

WINGDIAPI HDC   WINAPI CreateEnhMetaFileU( IN HDC, IN LPCSTR, IN CONST RECT *, IN LPCSTR);

WINGDIAPI HENHMETAFILE  WINAPI GetEnhMetaFileU( IN LPCSTR);

WINGDIAPI UINT  WINAPI GetEnhMetaFileDescriptionU( IN HENHMETAFILE, IN UINT,  OUT LPSTR );

WINGDIAPI BOOL WINAPI GetTextMetricsU( IN HDC, OUT LPTEXTMETRICA);

WINGDIAPI int WINAPI StartDocU(IN HDC, IN CONST DOCINFOA *);

WINGDIAPI int   WINAPI GetObjectU( IN HGDIOBJ, IN int, OUT LPVOID);

WINGDIAPI BOOL  WINAPI TextOutU( IN HDC, IN int, IN int, IN LPCSTR, IN int);

WINGDIAPI BOOL  WINAPI ExtTextOutU( IN HDC, IN int, IN int, IN UINT, IN CONST RECT *, IN LPCSTR, IN UINT, IN CONST INT *);

WINGDIAPI BOOL  WINAPI PolyTextOutU( IN HDC, IN CONST POLYTEXTA *, IN int);

WINGDIAPI int   WINAPI GetTextFaceU( IN HDC, IN int, OUT LPSTR);

WINGDIAPI DWORD WINAPI GetKerningPairsU( IN HDC, IN DWORD, OUT LPKERNINGPAIR);

WINGDIAPI BOOL        WINAPI GetLogColorSpaceU( IN HCOLORSPACE, OUT LPLOGCOLORSPACEA, IN DWORD);

WINGDIAPI HCOLORSPACE WINAPI CreateColorSpaceU( IN LPLOGCOLORSPACEA);

WINGDIAPI BOOL        WINAPI GetICMProfileU( IN HDC, IN OUT LPDWORD, OUT LPSTR);

WINGDIAPI BOOL        WINAPI SetICMProfileU( IN HDC, IN LPSTR);

WINGDIAPI int         WINAPI EnumICMProfilesU( IN HDC, IN ICMENUMPROCA, IN LPARAM);

WINGDIAPI BOOL        WINAPI UpdateICMRegKeyU( IN DWORD, IN LPSTR, IN LPSTR, IN UINT);

WINGDIAPI BOOL  WINAPI wglUseFontBitmapsU(HDC, DWORD, DWORD, DWORD);

WINGDIAPI BOOL  WINAPI wglUseFontOutlinesU(HDC, DWORD, DWORD, DWORD, FLOAT,
                                           FLOAT, int, LPGLYPHMETRICSFLOAT);

