#include "stdafx.h"
#include "wingdi_utf8.h"

WINGDIAPI int WINAPI AddFontResourceU(IN LPCSTR)
{
return WINGDIAPI int WINAPI AddFontResourceW(LPCSTR);
}

WINGDIAPI HMETAFILE WINAPI CopyMetaFileU( IN HMETAFILE, IN LPCSTR)
{
return HMETAFILE, IN LPCSTR);
}

WINGDIAPI HDC WINAPI CreateDCU( IN LPCSTR, IN LPCSTR, IN LPCSTR, IN CONST DEVMODEA *)
{
return LPCSTR, IN CONST DEVMODEA );
}

WINGDIAPI HFONT WINAPI CreateFontIndirectU( IN CONST LOGFONTA *)
{
return WINGDIAPI HFONT WINAPI CreateFontIndirectW( CONST LOGFONTA );
}

WINGDIAPI HFONT WINAPI CreateFontU( IN int, IN int, IN int, IN int, IN int, IN DWORD,
 IN DWORD, IN DWORD, IN DWORD, IN DWORD, IN DWORD,
 IN DWORD, IN DWORD, IN LPCSTR)
{
return DWORD,DWORD,DWORD, IN LPCSTR);
}

WINGDIAPI HDC WINAPI CreateICU( IN LPCSTR, IN LPCSTR, IN LPCSTR, IN CONST DEVMODEA *)
{
return LPCSTR, IN CONST DEVMODEA );
}

WINGDIAPI HDC WINAPI CreateMetaFileU( IN LPCSTR)
{
return WINGDIAPI HDC WINAPI CreateMetaFileW( LPCSTR);
}

WINGDIAPI BOOL WINAPI CreateScalableFontResourceU( IN DWORD, IN LPCSTR, IN LPCSTR, IN LPCSTR)
{
return LPCSTR, IN LPCSTR);
}

WINSPOOLAPI int WINAPI DeviceCapabilitiesU( IN LPCSTR, IN LPCSTR, IN WORD,
 OUT LPSTR, IN CONST DEVMODEA *)
{
return WORD,LPSTR, CONST DEVMODEA );
}

WINGDIAPI int WINAPI EnumFontFamiliesExU( IN HDC, IN LPLOGFONTA, IN FONTENUMPROCA, IN LPARAM, IN DWORD)
{
return LPARAM, IN DWORD);
}

WINGDIAPI int WINAPI EnumFontFamiliesU( IN HDC, IN LPCSTR, IN FONTENUMPROCA, IN LPARAM)
{
return FONTENUMPROCA, IN LPARAM);
}

WINGDIAPI int WINAPI EnumFontsU( IN HDC, IN LPCSTR, IN FONTENUMPROCA, IN LPARAM)
{
return FONTENUMPROCA, IN LPARAM);
}

WINGDIAPI BOOL WINAPI GetCharWidthU( IN HDC, IN UINT, IN UINT, OUT LPINT)
{
return UINT, LPINT);
}

WINGDIAPI BOOL WINAPI GetCharWidth32U( IN HDC, IN UINT, IN UINT, OUT LPINT)
{
return UINT, LPINT);
}

WINGDIAPI BOOL APIENTRY GetCharWidthFloatU( IN HDC, IN UINT, IN UINT, OUT PFLOAT)
{
return UINT, PFLOAT);
}

WINGDIAPI BOOL APIENTRY GetCharABCWidthsU( IN HDC, IN UINT, IN UINT, OUT LPABC)
{
return UINT, LPABC);
}

WINGDIAPI BOOL APIENTRY GetCharABCWidthsFloatU( IN HDC, IN UINT, IN UINT, OUT LPABCFLOAT)
{
return UINT, LPABCFLOAT);
}

WINGDIAPI DWORD WINAPI GetGlyphOutlineU( IN HDC, IN UINT, IN UINT, OUT LPGLYPHMETRICS, IN DWORD, OUT LPVOID, IN CONST MAT2 *)
{
return LPVOID, IN CONST MAT2 );
}

WINGDIAPI HMETAFILE WINAPI GetMetaFileU( IN LPCSTR)
{
return WINGDIAPI HMETAFILE WINAPI GetMetaFileW( LPCSTR);
}

WINGDIAPI UINT APIENTRY GetOutlineTextMetricsU( IN HDC, IN UINT, OUT LPOUTLINETEXTMETRICA)
{
return UINT, LPOUTLINETEXTMETRICA);
}

WINGDIAPI BOOL APIENTRY GetTextExtentPointU(
 IN HDC,
 IN LPCSTR,
 IN int,
 OUT LPSIZE
 )
{
return GetTextExtentPointW(HDC,LPCSTR,int,LPSIZE );
}

WINGDIAPI BOOL APIENTRY GetTextExtentPoint32U(
 IN HDC,
 IN LPCSTR,
 IN int,
 OUT LPSIZE
 )
{
return GetTextExtentPoint32W(HDC,LPCSTR,int,LPSIZE );
}

WINGDIAPI BOOL APIENTRY GetTextExtentExPointU(
 IN HDC,
 IN LPCSTR,
 IN int,
 IN int,
 OUT LPINT,
 OUT LPINT,
 OUT LPSIZE
 )
{
return GetTextExtentExPointW(HDC,LPCSTR,int,int,LPINT,LPINT,LPSIZE );
}

WINGDIAPI DWORD WINAPI GetCharacterPlacementU( IN HDC, IN LPCSTR, IN int, IN int, IN OUT LPGCP_RESULTSA, IN DWORD)
{
return LPGCP_RESULTSA, IN DWORD);
}

WINGDIAPI DWORD WINAPI GetGlyphIndicesU( IN HDC, IN LPCSTR, IN int, OUT LPWORD, IN DWORD)
{
return LPWORD, IN DWORD);
}

WINGDIAPI int WINAPI AddFontResourceExU( IN LPCSTR, IN DWORD, IN PVOID)
{
return DWORD, IN PVOID);
}

WINGDIAPI BOOL WINAPI RemoveFontResourceExU( IN LPCSTR, IN DWORD, IN PVOID)
{
return DWORD, IN PVOID);
}

WINGDIAPI HFONT WINAPI CreateFontIndirectExU( IN CONST ENUMLOGFONTEXDVA *)
{
return WINGDIAPI HFONT WINAPI CreateFontIndirectExW( CONST ENUMLOGFONTEXDVA );
}

WINGDIAPI BOOL WINAPI LineDDU( IN int, IN int, IN int, IN int, IN LINEDDAPROC, IN LPARAM)
{
return LINEDDAPROC, IN LPARAM);
}

WINGDIAPI HDC WINAPI ResetDCU(IN HDC, IN CONST DEVMODEA *)
{
return ResetDCW(HDC, IN CONST DEVMODEA );
}

WINGDIAPI BOOL WINAPI RemoveFontResourceU(IN LPCSTR)
{
return WINGDIAPI BOOL WINAPI RemoveFontResourceW(LPCSTR);
}

WINGDIAPI HENHMETAFILE WINAPI CopyEnhMetaFileU( IN HENHMETAFILE, IN LPCSTR)
{
return HENHMETAFILE, IN LPCSTR);
}

WINGDIAPI HDC WINAPI CreateEnhMetaFileU( IN HDC, IN LPCSTR, IN CONST RECT *, IN LPCSTR)
{
return , IN LPCSTR);
}

WINGDIAPI HENHMETAFILE WINAPI GetEnhMetaFileU( IN LPCSTR)
{
return WINGDIAPI HENHMETAFILE WINAPI GetEnhMetaFileW( LPCSTR);
}

WINGDIAPI UINT WINAPI GetEnhMetaFileDescriptionU( IN HENHMETAFILE, IN UINT, OUT LPSTR )
{
return UINT, UTF8_MAP());
}

WINGDIAPI BOOL WINAPI GetTextMetricsU( IN HDC, OUT LPTEXTMETRICA)
{
return HDC, LPTEXTMETRICA);
}

WINGDIAPI int WINAPI StartDocU(IN HDC, IN CONST DOCINFOA *)
{
return StartDocW(HDC, IN CONST DOCINFOA );
}

WINGDIAPI int WINAPI GetObjectU( IN HGDIOBJ, IN int, OUT LPVOID)
{
return int, LPVOID);
}

WINGDIAPI BOOL WINAPI TextOutU( IN HDC, IN int, IN int, IN LPCSTR, IN int)
{
return LPCSTR, IN int);
}

WINGDIAPI BOOL WINAPI ExtTextOutU( IN HDC, IN int, IN int, IN UINT, IN CONST RECT *, IN LPCSTR, IN UINT, IN CONST INT *)
{
return UINT, IN CONST INT );
}

WINGDIAPI BOOL WINAPI PolyTextOutU( IN HDC, IN CONST POLYTEXTA *, IN int)
{
return , IN int);
}

WINGDIAPI int WINAPI GetTextFaceU( IN HDC, IN int, OUT LPSTR)
{
return int, LPSTR);
}

WINGDIAPI DWORD WINAPI GetKerningPairsU( IN HDC, IN DWORD, OUT LPKERNINGPAIR)
{
return DWORD, LPKERNINGPAIR);
}

WINGDIAPI BOOL WINAPI GetLogColorSpaceU( IN HCOLORSPACE, OUT LPLOGCOLORSPACEA, IN DWORD)
{
return LPLOGCOLORSPACEA, IN DWORD);
}

WINGDIAPI HCOLORSPACE WINAPI CreateColorSpaceU( IN LPLOGCOLORSPACEA)
{
return WINGDIAPI HCOLORSPACE WINAPI CreateColorSpaceW( LPLOGCOLORSPACEA);
}

WINGDIAPI BOOL WINAPI GetICMProfileU( IN HDC, IN OUT LPDWORD, OUT LPSTR)
{
return LPDWORD, OUT LPSTR);
}

WINGDIAPI BOOL WINAPI SetICMProfileU( IN HDC, IN LPSTR)
{
return HDC, IN LPSTR);
}

WINGDIAPI int WINAPI EnumICMProfilesU( IN HDC, IN ICMENUMPROCA, IN LPARAM)
{
return ICMENUMPROCA, IN LPARAM);
}

WINGDIAPI BOOL WINAPI UpdateICMRegKeyU( IN DWORD, IN LPSTR, IN LPSTR, IN UINT)
{
return LPSTR, IN UINT);
}

WINGDIAPI BOOL WINAPI wglUseFontBitmapsU(HDC, DWORD, DWORD, DWORD)
{
return DWORD, DWORD);
}

WINGDIAPI BOOL WINAPI wglUseFontOutlinesU(HDC, DWORD, DWORD, DWORD, FLOAT,
 FLOAT, int, LPGLYPHMETRICSFLOAT)
{
return FLOAT,int, LPGLYPHMETRICSFLOAT);
}

