#!/bin/bash

if [ "$1" == "" ]; then
  echo Usage: $0 source
  exit -1
fi

BUILD=`grep ^PACKAGE_VERSION ../configure | sed "s/.*='\(.*\)'/\1/"`
echo $BUILD >version.inc

rm -rf $1-$BUILD-doc
mkdir $1-$BUILD-doc
mkdir $1-$BUILD-doc/html
xsltproc -stringparam chunker.output.encoding UTF8 -stringparam use.id.as.filename 1 -output $1-$BUILD-doc/html/ /usr/share/xml/docbook/stylesheet/nwalsh/html/chunk.xsl $1.dbk
xsltproc -output cvs.tex /usr/share/xml/docbook/stylesheet/db2latex/latex/docbook.xsl cvs.dbk
latex --interactive=batchmode cvs.tex
dvips cvs.dvi
texi2pdf cvs.tex
mv cvs.pdf $1-$BUILD-doc
mv cvs.ps $1-$BUILD-doc
tar czf $1-$BUILD-doc.tar.gz $1-$BUILD-doc/ 
rm -rf $1-$BUILD-doc/
