#!/bin/sh

# $Debian: cvs-makerepos,v 1.3 2001/06/14 03:06:06 epg Exp $

repository_create () {
    printf "Creating CVS repository in $1...\n"
    if [ ! -d $1 ]; then
	install -d -o root -g src -m 2775 $1
    fi
    cvs -d $1 init
}

if [ "$1" = "-d" ]; then
    . /usr/share/debconf/confmodule
	
    db_get cvs/repositories
    REPOS="$RET"
elif [ -f /etc/cvsnt/cron.conf ]; then
    . /etc/cvsnt/cron.conf
elif [ -f /etc/cvsnt/cvs.conf ]; then
    . /etc/cvsnt/cvs.conf
    REPOS="$CVS_REPOS"
fi

IFS=':'
for i in $REPOS; do
    IFS=' 	\
'
    if [ ! -d $i -o ! -d $i/CVSROOT ]; then
	repository_create $i
    fi
done
