#!/bin/sh

# $Debian: cvs-pserver,v 1.1 2001/04/20 16:00:54 epg Exp $

#
# Execute pserver
#

unset HOME
if [ -f /etc/cvsnt/pserver.conf ]; then
	. /etc/cvsnt/pserver.conf
elif [ -f /etc/cvsnt/cvs.conf ]; then
	. /etc/cvsnt/cvs.conf
else
	CVS_PSERV_REPOS=""
fi

allow_root_opts=""
OLDIFS="$IFS"
IFS=':'
for i in $CVS_PSERV_REPOS; do
	IFS="$OLDIFS"
	allow_root_opts="$allow_root_opts --allow-root=$i"
done
exec /usr/bin/cvs -b /usr/bin ${allow_root_opts} authserver

# End of file.
