#!/bin/bash

export DESTDIR=${PWD}/tmp
mkdir $DESTDIR
cd cvsnt
export LD_LIBRARY_PATH=/usr/local/lib/sparcv9
./configure --prefix=/usr --libdir=/usr/lib/sparcv9 --bindir=/usr/bin/sparcv9 CFLAGS=-m64 LDFLAGS=-m64 CPPFLAGS=-m64
make clean
make DESTDIR=${DESTDIR}
make install DESTDIR=${DESTDIR}
cd ${DESTDIR}
BUILD=`usr/bin/sparcv9/cvs -v | grep "(CVSNT)" | sed 's/.*CVSNT) \([^ ]*\).*/\1/'`
../make_package 64 ${BUILD}
cd ..
rm -rf $DESTDIR
