#!/bin/bash
PR=/Users/thoyle/cvs/Distribution_folder/Package_Root
cd cvsnt-2.0.51
./configure --prefix=/usr --with-config-dir=/private/etc/cvsnt
rm -rf ${PR}/* 
make DESTDIR=${PR}
make install DESTDIR=${PR}
mv ${PR}/usr/bin/cvsnt ${PR}/usr/bin/cvs
